"""Add live_plans table

Revision ID: 37119fd99439
Revises: 
Create Date: 2025-12-11 00:47:28.772256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37119fd99439'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if live_plans table exists before creating
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'live_plans' not in tables:
        # Create live_plans table
        op.create_table('live_plans',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('duration_hours', sa.Integer(), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('purposes', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('target_audience', sa.String(), nullable=False),
        sa.Column('preferred_time_start', sa.String(), nullable=True),
        sa.Column('preferred_time_end', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('difficulty', sa.String(), nullable=True),
        sa.Column('flow', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('preparations', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_live_plans_type'), 'live_plans', ['type'], unique=False)
        op.create_index(op.f('ix_live_plans_title'), 'live_plans', ['title'], unique=False)
    
    # Drop old tweet_metrics table if it exists
    if 'tweet_metrics' in tables:
        try:
            indexes = inspector.get_indexes('tweet_metrics')
            for idx in indexes:
                if idx['name'] == 'idx_tweet_user_snapshot':
                    op.drop_index('idx_tweet_user_snapshot', table_name='tweet_metrics')
                elif idx['name'] == 'ix_tweet_metrics_id':
                    op.drop_index('ix_tweet_metrics_id', table_name='tweet_metrics')
                elif idx['name'] == 'ix_tweet_metrics_tweet_id':
                    op.drop_index('ix_tweet_metrics_tweet_id', table_name='tweet_metrics')
                elif idx['name'] == 'ix_tweet_metrics_user_id':
                    op.drop_index('ix_tweet_metrics_user_id', table_name='tweet_metrics')
            op.drop_table('tweet_metrics')
        except Exception:
            pass  # Ignore errors
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop live_plans table
    op.drop_index(op.f('ix_live_plans_title'), table_name='live_plans')
    op.drop_index(op.f('ix_live_plans_type'), table_name='live_plans')
    op.drop_table('live_plans')
    # ### end Alembic commands ###
